// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: internal/infra/proto/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNKNOWN            EventType = 0
	EventType_EVENT_TYPE_OVERHEAT           EventType = 1
	EventType_EVENT_TYPE_MECHANICAL_WARNING EventType = 2
	EventType_EVENT_TYPE_VOLTAGE_DROP       EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNKNOWN",
		1: "EVENT_TYPE_OVERHEAT",
		2: "EVENT_TYPE_MECHANICAL_WARNING",
		3: "EVENT_TYPE_VOLTAGE_DROP",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNKNOWN":            0,
		"EVENT_TYPE_OVERHEAT":           1,
		"EVENT_TYPE_MECHANICAL_WARNING": 2,
		"EVENT_TYPE_VOLTAGE_DROP":       3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_infra_proto_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_internal_infra_proto_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_internal_infra_proto_event_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId        string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	EventType       EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=metron.event.v1.EventType" json:"event_type,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"` // Milissegundos desde a época Unix
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_infra_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_infra_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNKNOWN
}

func (x *Event) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

var File_internal_infra_proto_event_proto protoreflect.FileDescriptor

const file_internal_infra_proto_event_proto_rawDesc = "" +
	"\n" +
	" internal/infra/proto/event.proto\x12\x0fmetron.event.v1\"\x9b\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x129\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x1a.metron.event.v1.EventTypeR\teventType\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs*|\n" +
	"\tEventType\x12\x16\n" +
	"\x12EVENT_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13EVENT_TYPE_OVERHEAT\x10\x01\x12!\n" +
	"\x1dEVENT_TYPE_MECHANICAL_WARNING\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_VOLTAGE_DROP\x10\x03B>Z<github.com/CaueTech/metron-engine/internal/infra/proto;protob\x06proto3"

var (
	file_internal_infra_proto_event_proto_rawDescOnce sync.Once
	file_internal_infra_proto_event_proto_rawDescData []byte
)

func file_internal_infra_proto_event_proto_rawDescGZIP() []byte {
	file_internal_infra_proto_event_proto_rawDescOnce.Do(func() {
		file_internal_infra_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_proto_event_proto_rawDesc), len(file_internal_infra_proto_event_proto_rawDesc)))
	})
	return file_internal_infra_proto_event_proto_rawDescData
}

var file_internal_infra_proto_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_infra_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_infra_proto_event_proto_goTypes = []any{
	(EventType)(0), // 0: metron.event.v1.EventType
	(*Event)(nil),  // 1: metron.event.v1.Event
}
var file_internal_infra_proto_event_proto_depIdxs = []int32{
	0, // 0: metron.event.v1.Event.event_type:type_name -> metron.event.v1.EventType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_proto_event_proto_init() }
func file_internal_infra_proto_event_proto_init() {
	if File_internal_infra_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_proto_event_proto_rawDesc), len(file_internal_infra_proto_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_infra_proto_event_proto_goTypes,
		DependencyIndexes: file_internal_infra_proto_event_proto_depIdxs,
		EnumInfos:         file_internal_infra_proto_event_proto_enumTypes,
		MessageInfos:      file_internal_infra_proto_event_proto_msgTypes,
	}.Build()
	File_internal_infra_proto_event_proto = out.File
	file_internal_infra_proto_event_proto_goTypes = nil
	file_internal_infra_proto_event_proto_depIdxs = nil
}
