package proto

import {
	"github.com/CaueTech/metron-engine/internal/domain"
	"google.golang.org/protobuf/proto"
}

/*
	Note that the Event struct here is the Protobuf one, not from the domain. One is built upon the other
*/
func Serialize(event *domain.Event)([]byte, err]){
	protoEvent := &Event{
		Id:              event.ID().String(),
		SourceId:        event.SourceID().String(),
		EventType:       EventType(event.Type()),
		TimestampUnixMs: event.Timestamp().UnixMilli(),
	}

	// Some conversions were necessary to follow the standard generated by Protobuf in event.pb.go

	return proto.Marshal(protoEvent)
}