package proto

import (
	"errors"

	"github.com/CaueTech/metron-engine/internal/domain"
	"google.golang.org/protobuf/proto"
)

/*
	Note that the Event struct here is the Protobuf one, not from the domain. One is built upon the other
*/

var (
	ErrNullEvent = errors.New("event cannot be nil")
)

func Serialize(event *domain.Event) ([]byte, error) {
	if event == nil {
		return nil, ErrNullEvent
	}

	protoEvent := &Event{
		Id:              event.ID().String(),
		SourceId:        event.SourceID().String(),
		EventType:       EventType(event.Type()),
		TimestampUnixMs: event.Timestamp().UnixMilli(),
	}

	// Some conversions were necessary to follow the standard generated by Protobuf in event.pb.go

	// This function already returns a []byte, err
	return proto.Marshal(protoEvent)
}